apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-php-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-php-web-app
    #apps.tanzu.vmware.com/has-tests: true
  namespace: php
spec:
  build:
    env:
    - name: BP_PHP_WEB_DIR
      value: app
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  - name: clusterBuilder
    value: full
  source:
    git:
      url: https://github.com/fabianbrash/php-slim.git
      ref:
        branch: main
